# Generated by Django 5.0.14 on 2025-06-21 21:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiyat_cekme', '0003_bildirim'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bildirim',
            options={'ordering': ['-olusturma_zamani']},
        ),
        migrations.AddField(
            model_name='bildirim',
            name='notification_type',
            field=models.CharField(choices=[('info', 'Bilgi'), ('success', 'Başarılı'), ('warning', 'Uyarı'), ('danger', 'Hata')], default='info', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='default_category_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kategori',
            name='isim',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='kategori',
            unique_together={('isim', 'user')},
        ),
    ]
