# Generated by Django 4.2.23 on 2025-06-22 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fiyat_cekme', '0004_alter_bildirim_options_bildirim_notification_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogKategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('aciklama', models.TextField(blank=True)),
                ('olusturma_zamani', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Blog Kategorileri',
            },
        ),
        migrations.CreateModel(
            name='BlogYazisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('ozet', models.TextField(help_text='SEO için kısa açıklama', max_length=300)),
                ('icerik', models.TextField()),
                ('kapak_resmi', models.URLField(blank=True, null=True)),
                ('meta_title', models.CharField(blank=True, help_text='SEO başlığı (60 karakter)', max_length=60)),
                ('meta_description', models.CharField(blank=True, help_text='SEO açıklaması (160 karakter)', max_length=160)),
                ('anahtar_kelimeler', models.CharField(blank=True, help_text='Virgülle ayrılmış anahtar kelimeler', max_length=200)),
                ('yayinlandi', models.BooleanField(default=False)),
                ('olusturma_zamani', models.DateTimeField(auto_now_add=True)),
                ('guncelleme_zamani', models.DateTimeField(auto_now=True)),
                ('yayin_tarihi', models.DateTimeField(blank=True, null=True)),
                ('goruntulenme_sayisi', models.PositiveIntegerField(default=0)),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yazilar', to='fiyat_cekme.blogkategori')),
                ('yazar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_yazilari', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Blog Yazıları',
                'ordering': ['-yayin_tarihi', '-olusturma_zamani'],
            },
        ),
        migrations.CreateModel(
            name='SSS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soru', models.CharField(max_length=200)),
                ('cevap', models.TextField()),
                ('kategori', models.CharField(choices=[('genel', 'Genel'), ('fiyat', 'Fiyat Takibi'), ('teknik', 'Teknik'), ('hesap', 'Hesap Yönetimi')], default='genel', max_length=50)),
                ('sira', models.PositiveIntegerField(default=0)),
                ('aktif', models.BooleanField(default=True)),
                ('olusturma_zamani', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Sık Sorulan Sorular',
                'ordering': ['kategori', 'sira'],
            },
        ),
        migrations.AlterModelOptions(
            name='bildirim',
            options={'ordering': ['-olusturma_zamani'], 'verbose_name_plural': 'Bildirimler'},
        ),
        migrations.AlterModelOptions(
            name='eslesme',
            options={'verbose_name_plural': 'Eşleşmeler'},
        ),
        migrations.AlterModelOptions(
            name='kategori',
            options={'verbose_name_plural': 'Kategoriler'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name_plural': 'Kullanıcı Profilleri'},
        ),
        migrations.RenameField(
            model_name='eslesme',
            old_name='eklenme_zamani',
            new_name='olusturma_zamani',
        ),
        migrations.AlterUniqueTogether(
            name='kategori',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='license_months',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='license_start',
        ),
        migrations.AddField(
            model_name='kategori',
            name='olusturma_zamani',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='bildirim',
            name='mesaj',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='bildirim',
            name='notification_type',
            field=models.CharField(choices=[('info', 'Bilgi'), ('success', 'Başarılı'), ('warning', 'Uyarı'), ('error', 'Hata')], default='info', max_length=10),
        ),
        migrations.AlterField(
            model_name='eslesme',
            name='akakce_link',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='eslesme',
            name='site_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='BlogYorum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('icerik', models.TextField()),
                ('onaylandi', models.BooleanField(default=False)),
                ('olusturma_zamani', models.DateTimeField(auto_now_add=True)),
                ('yazi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yorumlar', to='fiyat_cekme.blogyazisi')),
            ],
            options={
                'verbose_name_plural': 'Blog Yorumları',
                'ordering': ['-olusturma_zamani'],
            },
        ),
    ]
